### ISSUE TITLE
Missing #pragma once

### ISSUE THREAD

**Issue by Dysman** [gwiazdorrr/CxxSwizzle#3]
Hi,
into file vector_functions.h is no "#pragma once" guard.
It's necessary for bigger projects which are nor only into one file.

Regards

**Comment by gwiazdorrr** [comment]
It is deliberately left out. You may want to include this file multiple times to define the functions in the namespace of your choice, so that they take precedence over other variants. The way ADL works, it is better to define a function in the namespace it is going to be used in rather than in libraries' one. 

Consider following code:
```
#include <cmath>
namespace test
{
   template <typename T> T sin(const T& angle);
}

float foo()
{
    using namespace test;
    return sin(0.0f);
}
```

Surprisingly it will be ::sin from <cmath> that gets called. If you change it to:

```
#include <cmath>
namespace test
{
   float sin(float angle);
}

float foo()
{
    using namespace test;
    return sin(0.0f);
}
```

You'll get ambiguity error. Only defining function in the same namespace in which it is called let's you "override" other global symbols safely.

That's why in the sample vector_functions.h is included inside glsl_sandbox namespace. Since CxxSwizzle defines scores of functions that share names with other global symbols (sin, for instance), this seemed to be the best way to work around conflicts.
